apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: dotnet-skaffold
build:
  artifacts:
  - image: dotnet-skaffold
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes/*
